### Listar los Productos

GET http://localhost:5000/productos

### Obtener un Producto por ID
GET http://localhost:5000/productos/2

### Buscar Productos por Nombre
GET http://localhost:5000/productos/search?nombre=Sony

### Buscar Productos por Precio
GET http://localhost:5000/productos/search?precio=18999

### Buscar Productos por Nombre y Precio
GET http://localhost:5000/productos/search?nombre=Sony&precio=4999

### Crear un Producto
POST http://localhost:5000/productos
Content-Type: application/json

{
  "nombre": "Xbox Controller",
  "precio": 1290,
  "descripcion": "Control inalámbrico con diseño ergonómico y compatibilidad multiplataforma.",
  "categoria_id": 2
}


### Actualizar un Producto por ID
PUT http://localhost:5000/productos/3
Content-Type: application/json

{
  "nombre": "Xbox Pro Controller",
  "precio": 3150.49,
  "descripcion": "Control inalámbrico con diseño ergonómico y compatibilidad multiplataforma. versión Pro con accesorios y botones extra.",
  "disponible": false,
  "categoria_id": 2
}

### Borrar un Producto por ID
DELETE http://localhost:5000/productos/2

# ### Obtener los Productos Disponibles
# GET http://localhost:5000/productos/disponibles


### Listar Categorías

GET http://localhost:5000/categorias

### Obtener una Categoría por ID

GET http://localhost:5000/categorias/4

### Crear una Categoría

POST http://localhost:5000/categorias
Content-Type: application/json

{
  "nombre": "Oficina"
}

### Actualizar una Categoría por ID

PUT http://localhost:5000/categorias/5
Content-Type: application/json

{
  "nombre": "Limpieza"
}

### Borrar una Categoría por ID

DELETE http://localhost:5000/categorias/6
